"""add pathing_graph to museum

Revision ID: 154fa9f6966b
Revises: 6ad48a1a699a
Create Date: 2026-08-26 22:11:14.156394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154fa9f6966b'
down_revision = '6ad48a1a699a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathing_graph', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.drop_column('pathing_graph')

    # ### end Alembic commands ###
