"""Update learning model

Revision ID: 1b09abc92b0f
Revises: 4fc2a1874c2f
Create Date: 2026-08-23 11:44:29.626686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b09abc92b0f'
down_revision = '4fc2a1874c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resources', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
