"""add video_url and media_status to objects

Revision ID: 2b5859dde3a1
Revises: cdfc64a710c1
Create Date: 2026-08-24 18:40:58.971241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5859dde3a1'
down_revision = 'cdfc64a710c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_column('media_status')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
