"""add floorplan overlay

Revision ID: 3fdc51e14691
Revises: 154fa9f6966b
Create Date: 2026-08-26 22:28:03.588552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdc51e14691'
down_revision = '154fa9f6966b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floorplan_image', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bounds_tl_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bounds_tl_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bounds_br_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bounds_br_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.drop_column('bounds_br_lng')
        batch_op.drop_column('bounds_br_lat')
        batch_op.drop_column('bounds_tl_lng')
        batch_op.drop_column('bounds_tl_lat')
        batch_op.drop_column('floorplan_image')

    # ### end Alembic commands ###
