"""Add audio and 3d model urls to objects

Revision ID: 40428e1a4ac0
Revises: a6c311c01499
Create Date: 2026-08-24 13:12:53.240482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40428e1a4ac0'
down_revision = 'a6c311c01499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('model_3d_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('objects', schema=None) as batch_op:
        batch_op.drop_column('model_3d_url')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
