"""Create learning_progress table

Revision ID: 5088b359b6e2
Revises: bf038bb3efe8
Create Date: 2026-08-23 12:21:55.096213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5088b359b6e2'
down_revision = 'bf038bb3efe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_id'], ['learning_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_id', name='uq_learning_progress_user')
    )
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_learning_id'), ['learning_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_learning_id'))

    op.drop_table('learning_progress')
    # ### end Alembic commands ###
