"""add indoor mapping facility coordinates to museum

Revision ID: 6ad48a1a699a
Revises: f95c3f471ca9
Create Date: 2026-08-26 21:23:32.649928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad48a1a699a'
down_revision = 'f95c3f471ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrance_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('entrance_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exit_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exit_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('washroom_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('washroom_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cafe_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cafe_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.drop_column('cafe_lng')
        batch_op.drop_column('cafe_lat')
        batch_op.drop_column('washroom_lng')
        batch_op.drop_column('washroom_lat')
        batch_op.drop_column('exit_lng')
        batch_op.drop_column('exit_lat')
        batch_op.drop_column('entrance_lng')
        batch_op.drop_column('entrance_lat')

    # ### end Alembic commands ###
