"""Add real fields to museum

Revision ID: be17270a2499
Revises: 7c0752181de5
Create Date: 2026-08-25 11:20:28.920376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be17270a2499'
down_revision = '7c0752181de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_hours', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wheelchair_access', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('info_desk', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cafe_restrooms', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.drop_column('cafe_restrooms')
        batch_op.drop_column('info_desk')
        batch_op.drop_column('wheelchair_access')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('opening_hours')

    # ### end Alembic commands ###
