"""Create bookmarks table

Revision ID: bf038bb3efe8
Revises: c089afc81755
Create Date: 2026-08-23 12:18:56.336941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf038bb3efe8'
down_revision = 'c089afc81755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_bookmark_user_content')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_content_type'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_content_id'))

    op.drop_table('bookmarks')
    # ### end Alembic commands ###
