"""Create activity_progress and user_history tables

Revision ID: c42efabce836
Revises: 5088b359b6e2
Create Date: 2026-08-23 12:23:56.944912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42efabce836'
down_revision = '5088b359b6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_history_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_history_content_type'), ['content_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_history_user_id'), ['user_id'], unique=False)

    op.create_table('activity_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_id', name='uq_activity_progress_user')
    )
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_progress_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_progress_activity_id'))

    op.drop_table('activity_progress')
    with op.batch_alter_table('user_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_history_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_history_content_type'))
        batch_op.drop_index(batch_op.f('ix_user_history_content_id'))

    op.drop_table('user_history')
    # ### end Alembic commands ###
